#!/usr/bin/env zsh
source $HOME/.config/sketchybar/vars.zsh
NAME=music

case $1 in
  "setup")
    sketchybar -m --add event song_update com.spotify.client.PlaybackStateChanged

    sketchybar -m                                     \
      --add item $NAME $POSITION                      \
      --set $NAME                                     \
          script="~/.config/sketchybar/plugins/music" \
          icon.drawing=off                            \
          drawing=off                                 \
          label.padding_left=$SPACE_2                 \
          label.padding_right=$SPACE_2                \
          label.color=$COLOR_INFO

    sketchybar -m --subscribe $NAME song_update

    ;;
  *) # UPDATE
    PLAYING=1
    if [ "$(echo "$INFO" | jq -r '.["Player State"]')" = "Playing" ]; then
      PLAYING=0
      TRACK="$(echo "$INFO" | jq -r .Name | cut -c1-20)"
      ARTIST="$(echo "$INFO" | jq -r .Artist | cut -c1-20)"
      ALBUM="$(echo "$INFO" | jq -r .Album | cut -c1-20)"
    fi


    args=()

    if [ $PLAYING -eq 0 ]; then
      if [ "$ARTIST" == "" ]; then
        args+=(--set $NAME label="$TRACK - $ALBUM" drawing=on)
      else
        args+=(--set $NAME label="$TRACK - $ARTIST" drawing=on)
      fi
    else
      args+=(--set $NAME drawing=off)
    fi

    sketchybar -m "${args[@]}"
    ;;
esac
