#!/usr/bin/env zsh
source $HOME/.config/sketchybar/vars.zsh
NAME=mode

case $1 in
  "setup")

    sketchybar                       \
      --add item $NAME $POSITION     \
      --set $NAME                    \
        drawing=no                   \
        icon.drawing=no              \
        label.color=$BLACK           \
        label.padding_left=$SPACE_2  \
        label.padding_right=$SPACE_2 \
        background.color=$COLOR_INFO \
        background.corner_radius=$RADIUS
        
    ;;
  "default")
    sketchybar --set $NAME label="" drawing=no
    ;;
  *)
    sketchybar --set $NAME label=$1 drawing=yes
    ;;
esac
