[[keyboard.bindings]]
chars = "\u001E"
key = "Key6"
mods = "Control"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[colors.normal]
black = "#0d0d10"
blue = "#81a2be"
cyan = "#8abeb7"
green = "#b5bd68"
magenta = "#F13279"
red = "#cc6666"
white = "#D4DFF2"
yellow = "#f0c674"

[colors.primary]
background = "#151D28"
foreground = "#D4DFF2"

[font]
size = 16.0

[font.bold_italic]
family = "IBM Plex Mono"
style = "SemiBold Italic"

[font.glyph_offset]
x = 0
y = 4

[font.italic]
family = "IBM Plex Mono"
style = "Light Italic"

[font.normal]
family = "IBM Plex Mono"
style = "Normal"

[font.offset]
x = 0
y = 8

[window]
decorations = "None"
dynamic_padding = true
opacity = 1

[window.padding]
x = 8
y = 8

[keyboard]
