#!/usr/bin/env zsh

if [[ "${NNNLVL:-0}" -ge 1 ]]; then
	echo "nnn is already running"
	return
fi

export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
\nnn -e "$@"

if [ -f "$NNN_TMPFILE" ]; then
	. "$NNN_TMPFILE"
	rm -f "$NNN_TMPFILE" > /dev/null
fi
