#!/usr/bin/env zsh
source $DOTDIR/sketchybar/vars.zsh
NAME="$(basename $0)"

if [[ $1 == "setup" ]]; then
  sketchybar                           \
    --add item "$NAME" $POSITION       \
    --set "$NAME"                      \
		script="$PLUGIN_DIR/battery"       \
		update_freq=30                     \
		background.padding_left=0          \
		background.padding_right=0         \
		icon.padding_left=0                \
    --subscribe $NAME system_woke
fi

STATUS=$(pmset -g batt)

if [[ $STATUS == "" ]]; then
  exit 0
fi

PERCENTAGE=$(echo $STATUS | grep -Eo '[0-9]+%' | cut -d% -f1)
CHARGING=$(echo $STATUS | grep 'AC Power')

if [[ $PERCENTAGE = "" ]]; then
  exit 0
fi

if [[ $CHARGING != "" ]]; then
	if [[ $PERCENTAGE -lt 80 ]]; then
		sketchybar --set $NAME                 \
			icon=""                             \
			icon.color="${WM_COLORS[green]}"     \
			label.color="${WM_COLORS[green]}"    \
			background.drawing=off               \
			label="${PERCENTAGE}%"
	else
		sketchybar --set $NAME                 \
			icon=""                             \
			icon.color="${WM_COLORS[green]}"     \
			background.drawing=off               \
			icon.drawing=on                      \
			label.drawing=off
	fi

elif [[ $PERCENTAGE -lt 5 ]]; then
	sketchybar --set $NAME                   \
		icon=" ‼"                             \
		icon.padding_left=$SPACE               \
		icon.padding_right=$SPACE              \
		icon.color="${WM_COLORS[white]}"       \
		icon.drawing="on"                      \
		label="${PERCENTAGE}%"                 \
		label.color="${WM_COLORS[white]}"      \
		background.drawing="on"                \
		background.color="${WM_COLORS[magenta]}"

elif [[ $PERCENTAGE -lt 10 ]]; then
	sketchybar --set $NAME                   \
		icon=" ‼ "                            \
		icon.color="${WM_COLORS[magenta]}"     \
		icon.drawing=on                        \
		background.drawing=off                 \
		label="${PERCENTAGE}%"                 \
		label.color="${WM_COLORS[magenta]}"

elif [[ $PERCENTAGE -lt 30 ]]; then
	sketchybar --set $NAME                   \
		icon=""                               \
		icon.color="${WM_COLORS[pink]}"        \
		icon.drawing=on                        \
		background.drawing=off                 \
		label="${PERCENTAGE}%"                 \
		label.color="${WM_COLORS[pink]}"

elif [[ $PERCENTAGE -lt 50 ]]; then
	sketchybar --set $NAME                   \
		icon=""                               \
		icon.color="${WM_COLORS[white]}"       \
		icon.drawing=on                        \
		background.drawing=off                 \
		label.drawing=off

elif [[ $PERCENTAGE -lt 80 ]]; then
	sketchybar --set $NAME                   \
		icon=""                               \
		icon.color="${WM_COLORS[white_alpha]}" \
		icon.drawing=on                        \
		background.drawing=off                 \
		label.drawing=off

else
	sketchybar --set $NAME                   \
		icon=""                               \
		icon.color="${WM_COLORS[white_alpha]}" \
		icon.drawing=on                        \
		background.drawing=off                 \
		label.drawing=off

fi
