#!/usr/bin/env zsh
source $DOTDIR/sketchybar/vars.zsh

if [[ $1 == "setup" ]]; then
  NAME=battery

  sketchybar                            \
    --add item $NAME $POSITION          \
    --set $NAME                         \
      script="$PLUGIN_DIR/battery"      \
      update_freq=30                    \
      background.padding_left=$SPACE_2  \
      background.padding_right=$SPACE_2 \
      icon.padding_left=$SPACE          \
      icon.padding_right=$SPACE         \
      label.padding_left=$SPACE         \
      label.padding_right=$SPACE        \
    --subscribe battery system_woke

fi

# UPDATE
STATUS=$(pmset -g batt)

if [[ $STATUS == "" ]]; then
  exit 0
fi

PERCENTAGE=$(echo $STATUS | grep -Eo '[0-9]+%' | cut -d% -f1)
CHARGING=$(echo $STATUS | grep 'AC Power')

if [[ $PERCENTAGE = "" ]]; then
  exit 0
fi

case ${PERCENTAGE%?} in
  [0-9]) PERCENTAGE=" ${PERCENTAGE}"
  ;;
  *) PERCENTAGE="${PERCENTAGE}"
esac

case ${PERCENTAGE} in
  9[0-9]|100) ICON=""
  ;;
  [6-8][0-9]) ICON=""
  ;;
  [3-5][0-9]) ICON=""
  ;;
  [1-2][0-9]) ICON=""
  ;;
  *) ICON=""
esac

if [[ $CHARGING != "" ]]; then
  ICON=""
fi

sketchybar --set $NAME icon="$ICON" label="${PERCENTAGE}%"
