#!/usr/bin/env zsh
source $HOME/.config/sketchybar/vars.zsh
NAME="$(basename $0)"
SELF="$PLUGIN_DIR/$NAME"

if [[ $1 == "setup" ]]; then
  sketchybar                                  \
    --add item $NAME $POSITION                \
    --set $NAME                               \
      update_freq=25                          \
      label.padding_left=0                    \
      label.padding_right=0                   \
			background.drawing=off                  \
			background.drawing=off                  \
			icon.drawing=off                        \
			icon.drawing=off                        \
			label.color="${WM_COLORS[pink]}" \
      script="$SELF"

fi

sketchybar --set $NAME label="$(date '+%y-%m-%d %H:%M KW%V')"
