#!/usr/bin/env zsh
source $HOME/.config/sketchybar/vars.zsh
NAME=front_app

if [[ $1 == "setup" ]]; then

  sketchybar                                                    \
    --add item $NAME $POSITION                                  \
    --set $NAME                                                 \
      script="$PLUGIN_DIR/front_app"                            \
      background.drawing=off                                    \
      label.drawing=on                                          \
      label.color=$WHITE                                        \
      label.padding_left=$SPACE_2                               \
      label.padding_right=$SPACE_2                              \
			label="$(yabai -m query --windows --window | jq  ".app")" \
      icon.drawing=off                                          \
    --subscribe front_app front_app_switched

fi

if [[ $1 == "hide" ]]; then
	sketchybar --set $NAME drawing=no
	exit
fi

if [[ $1 == "show" ]]; then
	sketchybar --set $NAME drawing=yes 
	exit
fi

# UPDATE

sketchybar --set $NAME label="$INFO"
