#!/usr/bin/env zsh
source $HOME/.config/sketchybar/vars.zsh

if [[ $1 == "setup" ]]; then
  NAME="layout"

  sketchybar                           \
    --add item $NAME $POSITION         \
    --set $NAME                        \
      script="$PLUGIN_DIR/layout"      \
      label.color=$COLOR_ACTIVE        \
      label.drawing=on                 \
      icon.drawing=off                 \
    --subscribe $NAME space_change

fi

# update

INFO=$(yabai -m query --spaces --space | jq -r .type)

case $INFO in
  "bsp") INFO="B" ;;
  "stack") INFO="S" ;;
  "float") INFO="F" ;;
esac

sketchybar --set "$NAME" label="$INFO"
