#!/usr/bin/env zsh
source $HOME/.config/sketchybar/vars.zsh
NAME="$(basename $0)"

if [[ "$1" == "setup" ]]; then
    sketchybar --add item $NAME $POSITION       \
      --set $NAME                               \
        drawing=no                              \
				width=200                               \
        icon.drawing=no                         \
        label.color="${WM_COLORS[black_alpha]}" \
        label.padding_left="$SPACE_2"           \
        label.padding_right="$SPACE_2"          \
        background.color="$COLOR_INFO"          \
        background.corner_radius="$RADIUS"

elif [[ $1 == "default" ]]; then
    sketchybar --set $NAME label="" drawing=no
    yabai -m config active_window_border_color $COLOR_ACTIVE window_border_width 2
		$HOME/.config/sketchybar/modules/front_app show

else
    COLOR="$COLOR_INFO"

    # second argument is optional and can set a color
    if [[ -n "$2" ]]; then
      if [[ -n "${WM_COLORS[$2]}" ]]; then
        COLOR="${WM_COLORS[$2]}"
      else
        echo "Invalid color: $2"
      fi
    fi

		$HOME/.config/sketchybar/modules/front_app hide
    sketchybar --set "$NAME" label="$1" drawing=yes background.color="$COLOR" width=600
    yabai -m config active_window_border_color "$COLOR"
fi

