#!/usr/bin/env zsh
source $HOME/.config/sketchybar/vars.zsh

update() {
  if [[ $SELECTED == true ]]; then

    sketchybar                         \
      --animate sin 20                 \
      --set $1                         \
        icon.color=$BLACK              \
        label.color=$GREEN             \
        background.color=$BLACK

  else

    sketchybar                      \
      --animate sin 20              \
      --set $1                      \
        icon.color=$COLOR_INACTIVE  \
        label.color=$WHITE_TRANS \
        background.color=$COLOR_ACTIVE_TRANSP

  fi
}

if [[ $1 == "setup" ]]; then
  SPACE_ICONS=("" "" "" "" "󰴙" "" "■" "⯅" "●")
  SPACE_LABELS=("SIDE" "MAIN" "COMM" "PLAN" "PLAY" "CHAT" "WRITE" "TODO" "PRIV")

  for i in {1..9}; do
    sid=$((i))

    sketchybar                         \
      --add space space.$sid $POSITION \
      --set space.$sid                 \
        associated_space=$sid          \
        icon=${SPACE_ICONS[i]}         \
        icon.drawing=off               \
        background.corner_radius=5     \
        background.height=24           \
        background.drawing=on          \
        background.padding_right=2     \
        background.padding_left=2      \
        label.drawing=on               \
        label.padding_right=4          \
        label.padding_left=4           \
        label=${SPACE_ICONS[$i]}       \
        label.font="$ICONFONT" \
        script="$PLUGIN_DIR/spaces"    \
        click_script="$PLUGIN_DIR/spaces click $sid" 

    update space.$sid
  done

  sketchybar                        \
    --add bracket primary_spaces    \
      space.1                       \
      space.2                       \
      space.3                       \
      space.4                       \
      space.5                       \
      space.6                       \
      space.7                       \
      space.8                       \
      space.9                       \
    --set primary_spaces            \
      background.color=$BLACK_ALPHA \
      background.corner_radius=5

  exit
fi

if [[ $1 == "click" ]]; then
  yabai -m space --focus $2
else
  update $NAME
fi

