#!/usr/bin/env zsh
source $HOME/.config/sketchybar/vars.zsh

SELF="$PLUGIN_DIR/spaces"
SPACE_ICONS=("󰖟" "" "" "" "󰴙" "󰙊" "エ" "ビ" "シ")

update() {
	local layout_type=$(yabai -m query --spaces --space | jq -r .type)

	if [[ ! $SELECTED == true ]]; then
		sketchybar --set $1 icon.color="${WM_COLORS[white_alpha]}"
	elif [[ $layout_type == "bsp" ]]; then
		sketchybar --set $1 icon.color="${WM_COLORS[white]}"
	elif [[ $layout_type == "float" ]]; then
		sketchybar --set $1 icon.color="${WM_COLORS[magenta]}"
	elif [[ $layout_type == "stack" ]]; then
		sketchybar --set $1 icon.color="${WM_COLORS[magenta]}"
	fi
}

if [[ $1 == "setup" ]]; then
  for i in {1..${#SPACE_ICONS}}; do
    sid=$((i))

    sketchybar --add space space.$sid $POSITION \
      --set space.$sid                          \
        associated_space=$sid                   \
        icon=${SPACE_ICONS[i]}                  \
        icon.drawing=on                         \
        icon.color=${WM_COLORS[black_alpha]}    \
        icon.padding_right=$SPACE               \
        background.drawing=off                  \
        background.padding_right=0              \
        background.padding_left=0               \
        label.drawing=off                       \
        label.padding_left=0                    \
        label.padding_right=0                   \
        script="$SELF"             \
        click_script="$SELF click $sid"

    update space.$sid
  done

fi

if [[ $1 == "click" ]]; then
  yabai -m space --focus $2
fi

if [[ -n $NAME  ]]; then
  update $NAME
fi

