#!/usr/bin/env zsh

SELF_PATH=$(realpath $0)
SELF_DIR=$(dirname $SELF_PATH)
SELF_NAME=$(basename $SELF_PATH)

usage() { cat <<EOF
  Usage $SELF_NAME [<chooser> [<action> [<args>]]]

  Options:
    -h, --help      Show this message

  Tasks:
    list
    view
    open

  Examples:
    choose
      -> lists available choosers with fzf

    choose bookmarks
      -> calls bookmarks chooser
      -> calls list of bookmarks
      -> pipes into fzf
      -> fzf uses --preview for each
      -> executes --action on selection
    choose --list bookmarks
    choose --preview bookmarks <selection>
EOF
}

pick () {
  ls -1 $SELF_DIR/chooser \
    | sed 's/\.zsh$//' \
    | fzf
}

zparseopts -D -E -A opts -help=h

if [[ -n ${opts[(i)--help]} || -n ${opts[(i):-h]} ]]; then
  usage
  exit 0
fi

CHOOSER=${1:-$(pick)}
if [[ -n $CHOOSER ]]; then
  CHOOSER_PATH="$SELF_DIR/chooser/$CHOOSER" 

  if [[ ! -f $CHOOSER_PATH ]]; then
    echo
    echo "Error: $CHOOSER is not a valid chooser"
    echo
    exit 1
  fi

   $CHOOSER_PATH
fi
