#!/usr/bin/env bash

current=$(gsettings get org.gnome.desktop.interface)

if [[ "$current" == *"dark"* ]]; then
    exec swaybg -m fill -i ~/Pictures/Wallpapers/dharmx-walls/monochrome/a_mountain_with_snow_on_it.jpg &
else
    exec swaybg -m fill -i ~/Pictures/Wallpapers/dharmx-walls/mountain/a_snowy_mountain_tops.jpg &
fi

