#!/usr/bin/env bash
source $HOME/.config/sketchybar/vars.zsh

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=display_added action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
# yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

yabai -m config                            \
  top_padding                16            \
  bottom_padding             16            \
  left_padding               16            \
  right_padding              16            \
                                           \
  window_gap                 24            \
  window_topmost             on            \
  window_border              on            \
  window_border_width        2             \
  window_border_radius       12            \
  window_placement           second_child  \
  window_opacity             off           \
  active_window_border_color $COLOR_ACTIVE \
  normal_window_border_color $COLOR_INACTIVE  \
                                           \
  insert_feedback_color      $COLOR_INFO   \
  mouse_modifier             fn            \
  mouse_action1              move          \
  mouse_action2              resize        \
  mouse_follows_focus        off           \
  focus_follows_mouse        off           \
                                           \
  split_type                 auto          \
  auto_balance               on            \
  layout                     bsp           \
  external_bar               main:40:0

yabai -m space 1 --layout bsp --label side    # side stuff, docs etc
yabai -m space 2 --layout bsp --label work    # main work stuff
yabai -m space 3 --layout bsp --label comm    # work related communication, teams, slack, mails
yabai -m space 4 --layout bsp --label plan    # calendar,
yabai -m space 5 --layout float --label play    # music, graphics, youtube
yabai -m space 6 --layout float --label chat    # discord etc

# these are usually on a second screen
yabai -m space 7 --layout bsp --label todo    # things etc
yabai -m space 8 --layout bsp --label note    # obsidian
yabai -m space 9 --layout bsp --label meep    # photos, messages.app

# Make thes windows float by default
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^System Preferences$" title=".*" manage=off
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Dash$" manage=off
yabai -m rule --add app="^Telephone$" manage=off
yabai -m rule --add app="^Hammerspoon Console$" manage=off
yabai -m rule --add title="Software Update" manage=off
yabai -m rule --add title="Cursor Pro" app="Cursor Pro" manage=off border=off 
yabai -m rule --add title="Setapp" manage=off
yabai -m rule --add app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="Raycast" manage=off
yabai -m rule --add app="Numi" manage=off sticky=on
yabai -m rule --add app="Stickies" manage=off sticky=on
yabai -m rule --add app="Obsidian" manage=off sticky=on
yabai -m rule --add title="New Note" manage=off sticky=on
yabai -m rule --add app="^(Calculator|System Preferences|Archive Utility)$" manage=off

# auto space assignments
yabai -m rule --add app="Microsoft Teams" space=comm
yabai -m rule --add title="Microsoft Teams Notifications" space=comm manage=off
# yabai -m rule --add app="MailMate" space=comm
# yabai -m rule --add app="Things" space=plan
yabai -m rule --add app="Discord" space=chat

printf "yabai: configuration loaded...\\n"
