$COLOR_YELLOW_50 = rgba(FCFCEDFF)
$COLOR_YELLOW_100 = rgba(FBF8D4FF)
$COLOR_YELLOW_200 = rgba(FBF18FFF)
$COLOR_YELLOW_300 = rgba(FCE531FF)
$COLOR_YELLOW_400 = rgba(F1CC00FF)
$COLOR_YELLOW_500 = rgba(E7B400FF)
$COLOR_YELLOW_600 = rgba(C88C00FF)
$COLOR_YELLOW_700 = rgba(A06300FF)
$COLOR_YELLOW_800 = rgba(884B04FF)
$COLOR_YELLOW_900 = rgba(733D14FF)
$COLOR_YELLOW_950 = rgba(431F0DFF)
$COLOR_BLUE_50 = rgba(EDF7FAFF)
$COLOR_BLUE_100 = rgba(D5EEF5FF)
$COLOR_BLUE_200 = rgba(B1E1F1FF)
$COLOR_BLUE_300 = rgba(87CCEAFF)
$COLOR_BLUE_400 = rgba(4AADE7FF)
$COLOR_BLUE_500 = rgba(188CE2FF)
$COLOR_BLUE_600 = rgba(1372C7FF)
$COLOR_BLUE_700 = rgba(1B66B3FF)
$COLOR_BLUE_800 = rgba(0E4E90FF)
$COLOR_BLUE_900 = rgba(184275FF)
$COLOR_BLUE_950 = rgba(132A47FF)
$COLOR_GREY_50 = rgba(F7F7F7FF)
$COLOR_GREY_100 = rgba(E9E9E9FF)
$COLOR_GREY_200 = rgba(CCCDCDFF)
$COLOR_GREY_300 = rgba(B1B1B2FF)
$COLOR_GREY_400 = rgba(969798FF)
$COLOR_GREY_500 = rgba(7C7D7FFF)
$COLOR_GREY_600 = rgba(636466FF)
$COLOR_GREY_700 = rgba(4B4D4EFF)
$COLOR_GREY_800 = rgba(343638FF)
$COLOR_GREY_900 = rgba(242628FF)
$COLOR_GREY_950 = rgba(1D1F21FF)
$COLOR_RED_50 = rgba(FDF2F3FF)
$COLOR_RED_100 = rgba(FCE3E4FF)
$COLOR_RED_200 = rgba(FCCBCBFF)
$COLOR_RED_300 = rgba(FAA6A4FF)
$COLOR_RED_400 = rgba(F4716FFF)
$COLOR_RED_500 = rgba(EC4948FF)
$COLOR_RED_600 = rgba(DB282DFF)
$COLOR_RED_700 = rgba(B91C1EFF)
$COLOR_RED_800 = rgba(991B1AFF)
$COLOR_RED_900 = rgba(7D201FFF)
$COLOR_RED_950 = rgba(430D0FFF)
$COLOR_ORANGE_50 = rgba(FEF7F0FF)
$COLOR_ORANGE_100 = rgba(FEEDDBFF)
$COLOR_ORANGE_200 = rgba(FBD7B5FF)
$COLOR_ORANGE_300 = rgba(FCB982FF)
$COLOR_ORANGE_400 = rgba(F88F42FF)
$COLOR_ORANGE_500 = rgba(F57624FF)
$COLOR_ORANGE_600 = rgba(E55E1DFF)
$COLOR_ORANGE_700 = rgba(BE451AFF)
$COLOR_ORANGE_800 = rgba(9A341AFF)
$COLOR_ORANGE_900 = rgba(7C2C1CFF)
$COLOR_ORANGE_950 = rgba(43140EFF)
$COLOR_GREEN_50 = rgba(F8FDECFF)
$COLOR_GREEN_100 = rgba(E5F6D2FF)
$COLOR_GREEN_200 = rgba(CFF2B3FF)
$COLOR_GREEN_300 = rgba(9AE28AFF)
$COLOR_GREEN_400 = rgba(88D06AFF)
$COLOR_GREEN_500 = rgba(7AC466FF)
$COLOR_GREEN_600 = rgba(4EA646FF)
$COLOR_GREEN_700 = rgba(318034FF)
$COLOR_GREEN_800 = rgba(23662DFF)
$COLOR_GREEN_900 = rgba(20562BFF)
$COLOR_GREEN_950 = rgba(0C2F19FF)
$COLOR_LILAC_50 = rgba(F5F4FAFF)
$COLOR_LILAC_100 = rgba(EAEAF7FF)
$COLOR_LILAC_200 = rgba(DADCF5FF)
$COLOR_LILAC_300 = rgba(C4C7EDFF)
$COLOR_LILAC_400 = rgba(A8ADDFFF)
$COLOR_LILAC_500 = rgba(8C94CBFF)
$COLOR_LILAC_600 = rgba(6F79B2FF)
$COLOR_LILAC_700 = rgba(5B6597FF)
$COLOR_LILAC_800 = rgba(49527BFF)
$COLOR_LILAC_900 = rgba(384060FF)
$COLOR_LILAC_950 = rgba(21283BFF)
$COLOR_STONE_50 = rgba(FAF9F7FF)
$COLOR_STONE_100 = rgba(F5F0EBFF)
$COLOR_STONE_200 = rgba(E8DFD6FF)
$COLOR_STONE_300 = rgba(D5C8BCFF)
$COLOR_STONE_400 = rgba(B8A99BFF)
$COLOR_STONE_500 = rgba(9A8B7DFF)
$COLOR_STONE_600 = rgba(7D6E61FF)
$COLOR_STONE_700 = rgba(635649FF)
$COLOR_STONE_800 = rgba(4D4139FF)
$COLOR_STONE_900 = rgba(3B312AFF)
$COLOR_STONE_950 = rgba(231E1AFF)
