# <CATEGORY>_<PROPERTY>_<INTENTION>_<VARIANT>_<STATE>
#
# COLOR_BACKGROUND_BRAND_SUBTLE_HOVER

$COLOR_BORDER_ACTIVE = $COLOR_GREEN_500
$COLOR_BORDER_INACTIVE = $COLOR_STONE_700
$COLOR_SHADOW_DEFAULT = $COLOR_GREY_950

$BORDER_SIZE = $BORDER_SIZE_1
$BORDER_SIZE_THIN = $BORDER_SIZE_1
$BORDER_SIZE_THICK = $BORDER_SIZE_3

$SPACE_XS = $SPACE_1
$SPACE_SM = $SPACE_2
$SPACE_MD = $SPACE_4
$SPACE_LG = $SPACE_12
$SPACE_XL = $SPACE_24
$SPACE_XXL = $SPACE_36

$SHADOW_OFFSET_X = $SPACE_3
$SHADOW_OFFSET_Y = $SPACE_3
$SHADOW_OFFSET = $SHADOW_OFFSET_X $SHADOW_OFFSET_Y
