require "baggage".from 'https://github.com/tpope/vim-fugitive'
require "baggage".from 'https://github.com/tpope/vim-repeat'
require "baggage".from 'https://github.com/tpope/vim-scriptease'
require "baggage".from 'https://github.com/tpope/vim-vinegar'
require "baggage".from 'https://github.com/tpope/vim-abolish'
require "baggage".from 'https://github.com/tpope/vim-eunuch'
