#!/usr/bin/env sh

# use gsettings montor changes to kill processes. restart handled by runit

gsettings monitor org.gnome.desktop.interface color-scheme | while read -r line; do
    pkill waybar
    pkill swaybg
done
