# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$hostname$directory${custom.jj_log}($git_state$git_branch$git_status)
$jobs$character
"""

[custom.jj_log]
when = """ jj workspace root """
format ="[tugging](blue) [$symbol($output )]($style)"
command = """
jj log -n 1 --no-graph -T 'bookmarks.map(|b| b.name())' -r 'heads(::@ & bookmarks())'
"""

[git_status]
modified = "[m](green)"
untracked = "[u](red)"
staged = "[s](yellow)"
renamed = "[r](magenta)"
deleted = "[d](red)"
style = "bright-black"
format = '[$all_status$ahead_behind]($style)'

[git_branch]
style = "green"

[directory]
truncation_length = 8
truncation_symbol = '…/'
style = "cyan"

[character]
success_symbol = "[\\$](purple)"
error_symbol = "[\\$](red)"
vimcmd_symbol = "[:](green)"
