#!/usr/bin/env sh
# TODO: create `nox-menu-files` that does this generically

cd "${DOTDIR}/services/.config/services"
file=$(fd run | fuzzel --dmenu --prompt="Open or create file in nvim:")

if [[ -z "$file" ]]; then
  exit 0
fi

kitty \
	--detach \
	--class="float.md" \
  -d $(pwd) \
	nvim $file

