#################
### AUTOSTART ###
#################

# Scratchpad applications
exec-once = [workspace special:term silent] kitty  
exec-once = [workspace special:term silent] kitty -e nvim ~/now
exec-once = [workspace special:notes silent] kitty --class scratchpad-notes -e nvim ~/now

# Common autostart items you might want:
exec-once = darkman run
exec-once = waybar
exec-once = vicinae server
exec-once = mako 
exec-once = hypridle
