# https://wiki.hypr.land/Configuring/

# See https://wiki.hypr.land/Configuring/Keywords/
$terminal = kitty
$fileManager = dolphin
$menu = vicinae

# See https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,12
env = ELECTRON_OZONE_PLATFORM_HINT,auto 

source = ./theme.conf
source = ./monitors.conf
source = ./autostart.conf
source = ./permissions.conf
source = ./input.conf
source = ./rules.conf
source = ./binds.conf

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true 
    preserve_split = true 
}
