

#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = eu
    kb_variant =
    kb_model =
    kb_rules =
    # For laptop: kb_options = ctrl:nocaps,altwin:swap_lalt_lwin
    # For desktop: kb_options = ctrl:nocaps
    # kb_options = ctrl:nocaps
    kb_options = ctrl:nocaps,altwin:swap_lalt_lwin
    follow_mouse = 0
    numlock_by_default = true

    sensitivity = 0.2 # Matching niri's accel-speed
    natural_scroll = true  # Matching niri's natural-scroll

    touchpad {
        natural_scroll = true  # Matching niri's natural-scroll
        tap-to-click = true  # Matching niri's tap
        disable_while_typing = true  # Matching niri's dwt
        scroll_factor = 1.0
    }
}

# Mouse configuration (matching niri)
device {
    name = epic-mouse-v1
    sensitivity = 0.2
    accel_profile = flat
}

# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
