
################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor=HDMI-A-1,preferred,0x0,1.0
monitor=eDP-1,preferred,560x1440,1.33
monitor=,preferred,auto,auto  # Fallback for other monitors

