# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrulev2=bordercolor $COLOR_BORDER_ACTIVE,fullscreen:1
windowrulev2=bordersize $BORDER_SIZE_THICK,fullscreen:1
windowrulev2=bordersize $BORDER_SIZE_THICK,fullscreenstate:0 2
windowrulev2=bordercolor $COLOR_YELLOW_500,fullscreenstate:0 2,title:.*,

# Floating windows
windowrulev2 = float, class:^(dmenu)$
windowrulev2 = float, class:^(firefox)$, title:^(Picture-in-Picture)$
windowrulev2 = float, title:^(1Password)$
windowrulev2 = float, class:^(waypaper)$
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(NautilusPreviewer)$

windowrulev2 = float, title:^(Gradia)$
windowrulev2 = size 1200 960 title:^(Gradia)$

windowrulev2 = size 960 800, class:^(pavucontrol)$
windowrulev2 = size 1200 960, class:^(NautilusPreviewer)$

# block from screen capture 
windowrulev2 = suppressevent screenrecord, class:^(1Password)$
windowrulev2 = suppressevent screenrecord, class:^(chrome-app\.fastmail)$
windowrulev2 = suppressevent screenrecord, title:^(Discord)$
windowrulev2 = suppressevent screenrecord, title:^(Cinny)$
windowrulev2 = suppressevent screenrecord, title:^(WhatsApp Web)$
windowrulev2 = suppressevent screenrecord, title:^(Microsoft Teams)$
