# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Ignore maximize requests from apps. You'll probably like this.
# windowrule = suppress_event maximize, class:.*
# Fix some dragging issues with XWayland
# windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# block from screen capture 
windowrule = match:title 1Password,suppress_event screenrecord
windowrule = match:title ^(chrome-app\.fastmail), suppress_event screenrecord
windowrule = match:title ^(Discord)$, suppress_event screenrecord
windowrule = match:title ^(Cinny)$, suppress_event screenrecord
windowrule = match:title ^(WhatsApp Web)$, suppress_event screenrecord
windowrule = match:title ^(Microsoft Teams)$, suppress_event screenrecord

windowrule = match:fullscreen 1, border_color $COLOR_BORDER_ACTIVE, border_size $BORDER_SIZE_THICK
windowrule = match:fullscreen_state_client 2, border_color $COLOR_YELLOW_500, border_size $BORDER_SIZE_THICK

windowrule = match:class ^(dmenu)$, float on
windowrule = match:title ^(1Password)$, float on
windowrule = match:class ^(pavucontrol)$, float on, size 960 800
windowrule = match:class ^(NautilusPreviewer)$, float on, size 1200 960
windowrule = match:class ^(Gradia)$, float on, size 1200 960

