workspace = 1, monitor:eDP-1, persistent:true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true
workspace = 4, monitor:HDMI-A-1, persistent:true
workspace = 5, monitor:HDMI-A-1, persistent:true
workspace = 6, monitor:HDMI-A-1, persistent:true

workspace = w[v1], gapsin:$SPACE_LG, gapsout:$SPACE_XL
workspace = w[v1]s[true], gapsin:$SPACE_LG, gapsout:$SPACE_XXL
workspace = f[0], gapsin:$SPACE_LG, gapsout:$SPACE_XXL
workspace = f[1], gapsout:$SPACE_XL

# workspace = w[tv2]s[false], gapsout:$SPACE_XL
# workspace = w[tv1]s[false], gapsout:$SPACE_LG

workspace = w[tv1]s[false]m[HDMI-A-1], gapsout:$SPACE_XL
workspace = w[tv2]m[HDMI-A-1], gapsin:$SPACE_LG, gapsout:$SPACE_XL
workspace = w[tv3]m[HDMI-A-1], gapsin:$SPACE_LG, gapsout:$SPACE_XL

