workspace = 1, monitor:eDP-1, persistent:true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true
workspace = 4, monitor:HDMI-A-1, persistent:true
workspace = 5, monitor:HDMI-A-1, persistent:true
workspace = 6, monitor:HDMI-A-1, persistent:true

workspace = name:special:term, gapsin:$SPACE_MD, gapsout:$SPACE_XL

# gapsout for single window workspaces, unless fullscreen
workspace = w[tv1]s[false], gapsout:$SPACE_MD
workspace = f[1]s[false], gapsout:0

