#!/usr/bin/env sh
source $HOME/.config/sketchybar/vars.sh

sketchybar --bar    height=32                         \
                    position=top                      \
                    sticky=on                         \
                    padding_left=8                    \
                    padding_right=8                   \
                    y_offset=8                        \
                    display=main                      \
                    margin=16                         \
                    corner_radius=$RADIUS             \
                    color=0x00000000                  \
                                                      \
          --default drawing=on                        \
                    label.font="$FONT"                \
                    background.padding_left=$SPACE_2  \
                    background.padding_right=$SPACE_2 \
                    background.corner_radius=$RADIUS  \
                    icon.padding_left=$SPACE          \
                    icon.padding_right=$SPACE         \
                    label.padding_left=$SPACE         \
                    label.padding_right=$SPACE        \
                    icon.font="$ICONFONT" 


export POSITION=left
  $PLUGIN_DIR/spaces.sh setup
  $PLUGIN_DIR/task.sh setup

export POSITION=right
  $PLUGIN_DIR/clock.sh setup
  $PLUGIN_DIR/battery.sh setup
  $PLUGIN_DIR/music setup
  $PLUGIN_DIR/skhd-mode setup

sketchybar                            \
  --add bracket sysinfo clock battery music \
  --set sysinfo                       \
      background.color=$BLACK_ALPHA   \
      background.corner_radius=5

export POSITION=center
  $PLUGIN_DIR/front_app.sh setup

echo "sketchybar configuration loaded.."
