#!/usr/bin/env zsh
source $DOTDIR/sketchybar/vars.zsh

sketchybar --bar    height=24                         \
                    position=top                      \
                    sticky=on                         \
                    padding_left=4                    \
                    padding_right=4                   \
                    y_offset=2                        \
                    display=main                      \
                    margin=2                          \
                    corner_radius=0                   \
                    color=0x00000000                  \
                                                      \
          --default drawing=on                        \
                    label.font="$FONT"                \
                    background.padding_left=$SPACE_2  \
                    background.padding_right=$SPACE_2 \
                    background.corner_radius=$RADIUS  \
                    icon.padding_left=$SPACE          \
                    icon.padding_right=$SPACE         \
                    label.padding_left=$SPACE         \
                    label.padding_right=$SPACE        \
                    icon.font="$ICONFONT" 


export POSITION=left
  $PLUGIN_DIR/spaces setup
  $PLUGIN_DIR/front_app setup

export POSITION=right
  $PLUGIN_DIR/clock setup
  $PLUGIN_DIR/skhd-mode setup
  $PLUGIN_DIR/layout setup
  $PLUGIN_DIR/music setup

sketchybar                          \
  --add bracket sysinfo clock music \
  --set sysinfo                     \
      background.color=$BLACK_ALPHA \
      background.corner_radius=5

export POSITION=center
  $PLUGIN_DIR/task setup

echo "sketchybar configuration loaded.."
