#!/usr/bin/env sh

current=$(gsettings get org.gnome.desktop.interface color-scheme)

if [[ "$current" == *"dark"* ]]; then
    exec waybar --style  ~/.config/waybar/dark.css
else
    exec waybar --style  ~/.config/waybar/light.css
fi

