#!/usr/bin/env zsh
local session_name=$(basename "${PWD##*/}" | tr . _)
local has_session=$(tmux has-session -t=$session_name 2>/dev/null)

if [[ $has_session != 0 ]]; then
	tmux new-session -ds "$session_name" -c "$PWD"
fi

if [[ -z $TMUX ]]; then
	tmux attach-session -t=$session_name
else
	tmux switch-client -t=$session_name
fi

