#!/usr/bin/env zsh
zparseopts -D -E -A opts -- n=use_nvim -nvim=use_nvim
local session_name=$(basename "${PWD##*/}" | tr . _)
local has_session=$(tmux has-session -t=$session_name 2>/dev/null)

if [[ $use_nvim ]]; then
	tmux new       -s "$session_name" -c "$PWD" -d
	# using send-keys so exiting nvim won't terminate the tmux session
	tmux send-keys -t "$session_name":1.1 "nvim" C-m

elif [[ $has_session != 0 ]]; then
	# note: use_nvim flag is exclusive with tm-launch
	tmux new-session -ds "$session_name" -c "$PWD" tm-launch

fi

if [[ -z $TMUX ]]; then
	tmux attach-session -t=$session_name
else
	tmux switch-client -t=$session_name
fi

