#!/usr/bin/env zsh
source $DOTDIR/sketchybar/vars.zsh

sketchybar                                     \
	--bar                                        \
		corner_radius=0                            \
		display=main                               \
		height=20                                  \
		margin=0                                   \
		padding_left=2                             \
		padding_right=2 \
		position=top                               \
		sticky=on                                  \
		y_offset=0                                 \
                                               \
	--default                                    \
		drawing=on                                 \
		background.corner_radius=$RADIUS           \
		background.drawing=on                      \
		background.padding_left=0                  \
		background.padding_right=$SPACE            \
		icon.font="$ICONFONT"                      \
		icon.padding_left=$SPACE                   \
		icon.padding_right=$SPACE                  \
		label.font="$FONT"                         \
		label.padding_left=$SPACE                  \
		label.padding_right=$SPACE                 

export POSITION=left
  $PLUGIN_DIR/spaces setup
  $PLUGIN_DIR/front_app setup

export POSITION=center
  $PLUGIN_DIR/skhd-mode setup

export POSITION=right
  $PLUGIN_DIR/battery setup
  $PLUGIN_DIR/clock setup
  $PLUGIN_DIR/music setup

echo "Sketchybar: started"
