#!/usr/bin/env zsh

FILE_INDEX=${FILE_INDEX:-"$HOME/file_index"}

SELF=$(realpath $0)
SELF_DIR=$(dirname $SELF)
SELF_NAME=$(basename $SELF)
SUBCOMMAND=${1:-pick}

source $SELF_DIR/../utils.zsh

list() {
  cat $FILE_INDEX
}

view() {
  bat $1
}

pick() {
  list | fzf                                \
      --ansi --keep-right --track --reverse \
      --preview "$SELF view {}"  \
      --bind "ctrl-h:toggle-preview"        
}

_check -q
eval "$SUBCOMMAND $@"
