#!/usr/bin/env sh

if [[ -n $WAYLAND_DISPLAY ]]; then
  exec swaybg -m tile -i ~/Pictures/Wallpapers/dharmx-walls/monochrome/a_black_and_white_photo_of_clouds.jpg
  exit 0
fi

echo "wallpaper/run: not on wayland"
