#!/usr/bin/env zsh

# read FILEPATH from stdin
# if stdin is empty, use current FILEPATH
# if stdin is not empty, use it as FILEPATH
if [ -t 0 ]; then
  FILEPATH=$(pwd)
else
  FILEPATH=$(cat)
fi

WINDOW_ID=$(yabai -m query --windows --space | jq '.[] | select(.app == "kitty") | .id' -e || echo error) # echoing error so that yabai focus will error too

yabai -m window --focus $WINDOW_ID 2>/dev/null \
  || kitty @ launch                            \
  || env | kitty -1
