#!/usr/bin/env zsh

case $(yabai -m query --spaces --space | jq -r '.type') in
  "bsp") yabai -m space --layout float ;;
  "stack") yabai -m space --layout bsp ;;
  "float") yabai -m space --layout stack ;;
esac

