-- if exists('$COLORTERM') && $COLORTERM == 'truecolor' && (system('defaults read -g AppleInterfaceStyle') =~? '^Dark')
--         set background=dark
--         colorscheme your_dark_theme
--     else
--         set background=light
--         colorscheme your_light_theme
--     endif
