#!/usr/bin/env zsh

local window_title=$(basename $0)
exec 2>/tmp/kitty-quick-window.log

DEFAULT_COMMAND="zsh"
if [[ -z $1 ]]; then
	COMMAND="$DEFAULT_COMMAND"
else
	COMMAND="$@ ; echo -e \"\\nany key to close\"; read -k1"
fi

launch () {
	kitty -1 -d="$HOME" --title="$window_title" zsh -c "$COMMAND" &> /tmp/kitty-quick-window.log &
}

launch &
